from typing import Protocol

from app.domain.cari import Cari
from app.domain.urun import Urun
from app.domain.teklif import Teklif


class CariRepositoryPort(Protocol):
    def list_all(self) -> list[Cari]: ...
    def get_by_id(self, entity_id: str) -> Cari | None: ...
    def create(self, cari: Cari) -> Cari: ...
    def update(self, cari: Cari) -> Cari | None: ...
    def delete(self, entity_id: str) -> bool: ...


class UrunRepositoryPort(Protocol):
    def list_all(self) -> list[Urun]: ...
    def get_by_id(self, entity_id: str) -> Urun | None: ...
    def create(self, urun: Urun) -> Urun: ...
    def update(self, urun: Urun) -> Urun | None: ...
    def delete(self, entity_id: str) -> bool: ...


class TeklifRepositoryPort(Protocol):
    def list_all(self) -> list[Teklif]: ...
    def get_by_id(self, entity_id: str) -> Teklif | None: ...
    def create(self, teklif: Teklif) -> Teklif: ...
    def update(self, teklif: Teklif) -> Teklif | None: ...
