from typing import TYPE_CHECKING, Optional, Protocol

from django.db.models import QuerySet

if TYPE_CHECKING:
    from apps.catalog.models import Category, Product
    from apps.orders.models import Order


class CategoryRepositoryProtocol(Protocol):
    def get_by_id(self, pk: int) -> Optional["Category"]: ...

    def get_by_slug(self, slug: str) -> Optional["Category"]: ...

    def get_root_categories(self) -> QuerySet["Category"]: ...

    def get_active_children(self, parent_id: int) -> QuerySet["Category"]: ...


class ProductRepositoryProtocol(Protocol):
    def get_by_id(self, pk: int) -> Optional["Product"]: ...

    def get_by_slug(self, slug: str) -> Optional["Product"]: ...

    def get_by_category(self, category_id: int, active_only: bool = True) -> QuerySet["Product"]: ...

    def get_active_products(self) -> QuerySet["Product"]: ...

    def search(self, query: str) -> QuerySet["Product"]: ...

    def decrement_stock(self, product_id: int, quantity: int) -> None: ...


class OrderRepositoryProtocol(Protocol):
    def get_by_id(self, pk: int) -> Optional["Order"]: ...

    def get_user_orders(self, user_id: int) -> QuerySet["Order"]: ...

    def create_order(self, order_data: dict) -> "Order": ...

    def update_status(self, order_id: int, status: str) -> "Order": ...
