from typing import Protocol

from school.models import Department, Student


class DepartmentRepository(Protocol):
    def list_all(self) -> list[Department]: ...
    def get_by_id(self, department_id: int) -> Department | None: ...
    def create(self, name: str) -> Department: ...
    def update(self, department: Department, name: str) -> Department: ...
    def delete(self, department: Department) -> None: ...
    def name_exists(self, name: str, exclude_pk: int | None = None) -> bool: ...


class StudentRepository(Protocol):
    def list_all(self) -> list[Student]: ...
    def get_by_id(self, student_id: int) -> Student | None: ...
    def create(
        self,
        *,
        student_number: str,
        first_name: str,
        last_name: str,
        birth_date,
        department_id: int,
    ) -> Student: ...
    def update(
        self,
        student: Student,
        *,
        student_number: str,
        first_name: str,
        last_name: str,
        birth_date,
        department_id: int,
    ) -> Student: ...
    def delete(self, student: Student) -> None: ...
    def department_exists(self, department_id: int) -> bool: ...
    def student_number_exists(self, student_number: str, exclude_pk: int | None = None) -> bool: ...
